services:
  mariadb-pdp:
    image: mariadb:latest
    ports:
      - "53306:3306"
    expose:
      - "3306"
    volumes:
      - ./config/pdp.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pos
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: Europe/Bucharest
    networks:
      - pdp_net

  mongodb-consult:
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: pos
      TZ: Europe/Bucharest
    networks:
      - consult_net

  mariadb-idm:
    image: mariadb:latest
    ports:
      - "53307:3306"
    expose:
      - "3306"
    volumes:
      - ./config/idm.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: IDM
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
      TZ: Europe/Bucharest
    networks:
      - idm_net

  redis_idm:
    image: redis:latest
    expose:
      - "6379"
    networks:
      - idm_net

  pdp-service:
    build:
      context: ./PDP/
      dockerfile: Dockerfile
    container_name: pdp-service
    ports:
      - "8081:8080"
    expose:
      - "8080"
    networks:
      - pdp_net
      - gateway_net
    depends_on:
      - mariadb-pdp
    restart: on-failure:10

  idm-service:
    build:
      context: ./IDM/
      dockerfile: Dockerfile
    container_name: idm-service
    ports:
      - "9090:9090"
    expose:
      - "9090"
    networks:
      - idm_net
      - gateway_net
    depends_on:
      - mariadb-idm
      - redis_idm
    restart: on-failure:10

  consult-service:
    build:
      context: ./Consult/
      dockerfile: Dockerfile
    container_name: consult-service
    ports:
      - "8083:8080"
    expose:
      - "8080"
    networks:
      - consult_net
      - gateway_net
    depends_on:
      - mongodb-consult
    restart: on-failure:10

  gateway-service:
    build:
      context: ./Gateway/
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - gateway_net
    depends_on:
      - pdp-service
      - idm-service
      - consult-service
    restart: on-failure:10

networks:
  idm_net:
  pdp_net:
  consult_net:
  gateway_net:
